services:
  db:
    image: mariadb:10.6
    container_name: mariadb_hogwarts_ejm
    restart: always
    env_file:
      - .env
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "4306:3306"
